version: "3.8"

services:
  joblisting-service:
    image: "${DOCKER_USERNAME}/joblisting:v1"
    build:
      context: ./JoblistingService
      dockerfile: Dockerfile
    environment:
      - MongoDbSettings__ConnectionString=${MONGO_CONNECTION_STRING}
      - MongoDbSettings__DatabaseName=${MONGO_DATABASE_NAME}
    ports:
      - "8082:8080" # Maps localhost:8082 to container's 8080
