apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.Development.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: joblisting-service
  name: joblisting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: joblisting-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker-compose.Development.yml
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: joblisting-service
    spec:
      containers:
        - env:
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: joblisting-secret
                  key: MongoDbSettings__ConnectionString
            - name: MongoDbSettings__DatabaseName
              valueFrom:
                secretKeyRef:
                  name: joblisting-secret
                  key: MongoDbSettings__DatabaseName
            - name: Redis__ConnectionString
              value: redis:6379
          image: hobingantuk/joblisting-services:prod
          imagePullPolicy: Always
          name: joblisting-service
          ports:
            - containerPort: 9002
              protocol: TCP
          resources:
            requests:
              memory: 128Mi  # Reduce to match observed usage (e.g., 22-25Mi)
              cpu: 50m       # Reduce since actual usage is much lower (~1m)
            limits:
              memory: 256Mi  # Set a reasonable upper bound for spikes
              cpu: 200m      # Limit CPU to a safe maximum without over-provisioning\
      restartPolicy: Always
