apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.Development.yml
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: joblisting-service
  name: joblisting-service
spec:
  ports:
    - name: "9002"
      port: 9002
      targetPort: 9002
  selector:
    io.kompose.service: joblisting-service
