name: Build Img Workflow

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read
  id-token: write  # Allow id-token for nested workflows

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 2: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set Image Tag Based on Branch
      - name: Set Docker Image Tag
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "IMAGE_TAG=joblisting-services:prod" >> $GITHUB_ENV
          elif [[ "${{ github.ref_name }}" == "dev" ]]; then
            echo "IMAGE_TAG=joblisting-services:dev" >> $GITHUB_ENV
          fi

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./JoblistingService
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}

  deploy:
    needs: build
    if: github.ref_name == 'main'  # Only trigger on the main branch
    uses: ./.github/workflows/DeployToGKE.yml
    secrets: inherit