name: CD Workflow

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Set Environment Variables for Service
      - name: Set Environment Variables for Service
        env:
          SERVICE_FOLDER: "JoblistingService"
          IMAGE_TAG: "joblisting:v1"
        run: |
          echo "SERVICE_FOLDER=${SERVICE_FOLDER}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          
      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./${{ env.SERVICE_FOLDER }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}
      
      # Step 4: Deploy with Docker Compose
      - name: Deploy with Docker Compose
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          MONGO_DATABASE_NAME: ${{ secrets.MONGO_DATABASE_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker-compose -f ./docker-compose.yml up -d