# .github/workflows/cd.yml
name: CD Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set Environment Variables for Service
        env:
          SERVICE_FOLDER: "JoblistingService"
          IMAGE_TAG: "joblisting:v1"
        run: |
          echo "SERVICE_FOLDER=${SERVICE_FOLDER}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        env:
          APP_UID: 1000
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker buildx build --platform linux/amd64,linux/arm64 \
          -t ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }} ./${{ env.SERVICE_FOLDER }}
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}      
          
      - name: Deploy with Docker Compose
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          MONGO_DATABASE_NAME: ${{ secrets.MONGO_DATABASE_NAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          docker-compose -f ./docker-compose.yml up -d