name: CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Set Environment Variables for Service
      - name: Set Environment Variables for Service
        env:
          SERVICE_FOLDER: "JoblistingService"
          IMAGE_TAG: "joblisting:v1"
        run: |
          echo "SERVICE_FOLDER=${SERVICE_FOLDER}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: ./${{ env.SERVICE_FOLDER }}
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}