name: Deploy Joblisting to GKE

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      # Step 1: Check out code
      - name: Check out code
        uses: actions/checkout@v3

      # Step 2: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ secrets.GKE_PROJECT }}/locations/global/workloadIdentityPools/github-action-pool/providers/github-action-provider"
          service_account: ${{ secrets.GKE_SERVICE_ACCOUNT }}

      # Step 3: Configure kubectl with GKE credentials
      - name: Configure GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: careermatch
          location: europe-west4
          project_id: ${{ secrets.GKE_PROJECT_ID }}

      # Step 4: Create Kubernetes Secrets
      - name: Create Kubernetes Secrets
        run: |
          kubectl create secret generic joblisting-secret \
            --from-literal=MongoDbSettings__ConnectionString="${{ secrets.MONGO_CONNECTION_STRING }}" \
            --from-literal=MongoDbSettings__DatabaseName="${{ secrets.MONGO_DATABASE_NAME }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      # Step 5: Deploy to GKE
      - name: Deploy to GKE
        run: |
          kubectl apply -f ./k8s-manifests/